kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ibmi-mcp-server
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ibmi-mcp-server:latest'
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: "https://github.com/IBM/ibmi-mcp-server.git"
      ref: main
    contextDir: server
  triggers:
    - type: ConfigChange