[project]
name = "ibmi-agent-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adam Shedivy", email = "ajshedivyaj@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "agno>=2.1.0",
    "google-adk>=1.19.0",
    "ibm-watsonx-ai>=1.4.4",
    "langchain-mcp-adapters>=0.1.12",
    "mcp>=1.16.0",
    "openai>=2.6.1",
]

[project.scripts]
ibmi-agent-sdk = "ibmi_agent_sdk:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.13.3",
]
